src/main/java/com/gmail/fursovych20/entity/Subscription.java
package com.gmail.fursovych20.entity;

import java.io.Serializable;
import java.time.LocalDate;

public class Subscription implements Serializable{

	private static final long serialVersionUID = -6271585104911424635L;

	private int id;
	private int userId;
	private int publicationId;
	private LocalDate startLocaleDate;
	private LocalDate endLocaleDate;
	private double price;

	public Subscription() {
		super();
	}
	private SubscriptionStatus status;

	/**
	 * Builder for build subscription
	 */
	public static class Builder{

		private final Subscription subscription;

		public Builder() {
			this.subscription = new Subscription();
		}

		public Subscription.Builder setId(int id){
			subscription.setId(id);
			return this;
		}

		public Subscription.Builder setUserId(int userId){
			subscription.setUserId(userId);
			return this;
		}

		public Subscription.Builder setPublicationId(int publicationId){
			subscription.setPublicationId(publicationId);
			return this;
		}

		public Subscription.Builder setStartLocalDate(LocalDate startDate){
			subscription.setStartLocalDate(startDate);
			return this;
		}

		public Subscription.Builder setEndLocalDate(LocalDate endDate){
			subscription.setEndLocalDate(endDate);
			return this;
		}

		public Subscription.Builder setPrice(double price){
			subscription.setPrice(price);
			return this;
		}

		public Subscription.Builder setStatus(SubscriptionStatus status){
			subscription.setStatus(status);
			return this;
		}

		public Subscription build(){
			return subscription;
		}

	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getPublicationId() {
		return publicationId;
	}

	public void setPublicationId(int publicationId) {
		this.publicationId = publicationId;
	}

	public LocalDate getStartLocalDate() {
		return startLocaleDate;
	}

	public void setStartLocalDate(LocalDate startDate) {
		this.startLocaleDate = startDate;
	}

	public LocalDate getEndLocalDate() {
		return endLocaleDate;
	}

	public void setEndLocalDate(LocalDate endDate) {
		this.endLocaleDate = endDate;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public SubscriptionStatus getStatus() {
		return status;
	}

	public void setStatus(SubscriptionStatus status) {
		this.status = status;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((endLocaleDate == null) ? 0 : endLocaleDate.hashCode());
		result = prime * result + id;
		long temp;
		temp = Double.doubleToLongBits(price);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + publicationId;
		result = prime * result + ((startLocaleDate == null) ? 0 : startLocaleDate.hashCode());
		result = prime * result + ((status == null) ? 0 : status.hashCode());
		result = prime * result + userId;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Subscription other = (Subscription) obj;
		if (endLocaleDate == null) {
			if (other.endLocaleDate != null)
				return false;
		} else if (!endLocaleDate.equals(other.endLocaleDate))
			return false;
		if (id != other.id)
			return false;
		if (Double.doubleToLongBits(price) != Double.doubleToLongBits(other.price))
			return false;
		if (publicationId != other.publicationId)
			return false;
		if (startLocaleDate == null) {
			if (other.startLocaleDate != null)
				return false;
		} else if (!startLocaleDate.equals(other.startLocaleDate))
			return false;
		if (status != other.status)
			return false;
		return userId == other.userId;
	}

	@Override
	public String toString() {
		return "Subscription [id=" + id + ", userId=" + userId + ", publicationId=" + publicationId + ", startDate="
				+ startLocaleDate + ", endDate=" + endLocaleDate + ", price=" + price + ", status=" + status + "]";
	}

}

src/main/java/com/gmail/fursovych20/entity/User.java
package com.gmail.fursovych20.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class User implements Serializable{

	private static final long serialVersionUID = -4210715155698940106L;
	
	private Integer id;
	private String login;
	private String password;
	private String name;
	private String surName;
	private String email;
	private BigDecimal balance;
	private Role role;
	
	public User() {
		super();
	}
	
	/**
	 * Builder for build user
	 */
	public static class Builder {
		private final User user;

		public Builder() {
			this.user = new User();
		}

		public Builder setId(Integer id) {
			user.setId(id);
			return this;
		}

		public Builder setLogin(String login) {
			user.setLogin(login);
			return this;
		}

		public Builder setPassword(String password) {
			user.setPassword(password);
			return this;
		}

		public Builder setName(String name) {
			user.setName(name);
			return this;
		}

		public Builder setSetSurName(String surName) {
			user.setSurName(surName);
			return this;
		}

		public Builder setEmail(String email) {
			user.setEmail(email);
			return this;
		}

		public Builder setBalance(BigDecimal balance) {
			user.setBalance(balance);
			return this;
		}

		public Builder setRole(Role role) {
			user.setRole(role);
			return this;
		}

		public User build() {
			return user;
		}
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurName() {
		return surName;
	}

	public void setSurName(String surName) {
		this.surName = surName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public BigDecimal getBalance() {
		return balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		long temp;
		temp = balance.longValue();
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + ((email == null) ? 0 : email.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((login == null) ? 0 : login.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((password == null) ? 0 : password.hashCode());
		result = prime * result + ((role == null) ? 0 : role.hashCode());
		result = prime * result + ((surName == null) ? 0 : surName.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		User other = (User) obj;
		if (!balance.equals(other.balance))
			return false;
		if (email == null) {
			if (other.email != null)
				return false;
		} else if (!email.equals(other.email))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (login == null) {
			if (other.login != null)
				return false;
		} else if (!login.equals(other.login))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (password == null) {
			if (other.password != null)
				return false;
		} else if (!password.equals(other.password))
			return false;
		if (role != other.role)
			return false;
		if (surName == null) {
			return other.surName == null;
		} else return surName.equals(other.surName);
	}

	@Override
	public String toString() {
		return "User [id=" + id + ", login=" + login + ", password=" + password + ", name=" + name + ", surName="
				+ surName + ", email=" + email + ", balance=" + balance + ", role=" + role + "]";
	}	

}

src/main/webapp/WEB-INF/jsp/user/avaliable_issues.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<jsp:useBean id="currentDate" class="java.util.Date" />

<fmt:setLocale value="${sessionScope.locale}"/>	
<fmt:bundle basename="localization.local" prefix = "issues_page.">
	<fmt:message key="title" var="title"/>
	<fmt:message key="date_of_publication" var="date_of_publication"/>
	<fmt:message key="description" var="description"/>
	<fmt:message key="no_issues" var="no_issues"/>
	<fmt:message key="show_button" var="show_button"/>
</fmt:bundle>

<!DOCTYPE html>
<html>
	<head>
		<c:set var="contextPath" value="${pageContext.request.contextPath}" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>${title}</title>
		<link href="<c:url value="/resources/css/bootstrap/bootstrap.min.css" />" rel="stylesheet">
		
	</head>
<body>
	
	<%@include file="/WEB-INF/jsp/nav.jsf" %>

	<div class="container-fluid" style="margin-top: 60px">
      <div class="row">
        
        <%@include file="user-nav.jsf" %>
        
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4"><div style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;" class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>

          <h2>${title}</h2>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>${date_of_publication}</th>
                  <th>${description}</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
              	<c:forEach items="${issues}" var="issue">
              		<tr>
              			<td>${issue.localDateOfPublication}</td>
	              		<td>${issue.description}</td>
	              		<td><form method="get" action="${contextPath}/controller/user/show-issue-file">
		                	<input type="hidden" name="issue_id" value="${issue.id}"/>
		                	<button type="submit" class="btn btn-primary">${show_button }</button>
		                </form></td>		               	                
		            </tr>
              	</c:forEach>
              </tbody>
            </table>
            <c:if test="${issues.size() == 0}">
            	<br>
            	<h3>${no_issues }</h3>
            </c:if>
          </div>
        </main>
      </div>
    </div>
    
</body>
</html>

src/main/webapp/WEB-INF/jsp/user/balance_operation_history.jsp
<%--
  Created by IntelliJ IDEA.
  User: lenovo
  Date: 29.07.2022
  Time: 20:44
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java"
         pageEncoding="UTF-8" %>

<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@page import="com.gmail.fursovych20.entity.BalanceOperationType" %>

<fmt:setLocale value="${sessionScope.locale}"/>
<fmt:bundle basename="localization.local" prefix="balance_operation_history_page.">
    <fmt:message key="title" var="title"/>
    <fmt:message key="date_header" var="date_header"/>
    <fmt:message key="money" var="money"/>
    <fmt:message key="sum_header" var="sum_header"/>
    <fmt:message key="type_header" var="type_header"/>
    <fmt:message key="refund_operation" var="refund_operation"/>
    <fmt:message key="payment_of_subscriptions_operation" var="payment_of_subscriptions_operation"/>
    <fmt:message key="balance_replenishment_operation" var="balance_replenishment_operation"/>
</fmt:bundle>

<c:set var="counter" value="${1}"/>

<!DOCTYPE html>
<html>
<head>
    <c:set var="contextPath" value="${pageContext.request.contextPath}"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>${title}</title>
    <link href="<c:url value="/resources/css/bootstrap/bootstrap.min.css"/>" rel="stylesheet"/>
</head>
<body>
<%@include file="/WEB-INF/jsp/nav.jsf" %>
<div class="container-fluid" style="margin-top: 60px">
    <div class="row">
        <%@include file="user-nav.jsf" %>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            <div style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"
                 class="chartjs-size-monitor">
                <div class="chartjs-size-monitor-expand"
                     style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;">
                    <div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div>
                </div>
                <div class="chartjs-size-monitor-shrink"
                     style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;">
                    <div style="position:absolute;width:200%;height:200%;left:0; top:0"></div>
                </div>
            </div>
            <h2>${title}</h2>
            <div class="table-responsive">
                <table class="table table-striped table-sm">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>${date_header}</th>
                        <th>${sum_header}, ${money}</th>
                        <th>${type_header}</th>
                        <th>${status_header}</th>
                    </tr>
                    </thead>
                    <tbody>
                        <c:forEach items="${balance_operations}" var="operation">
                            <tr>
                                <td>${counter}</td>
                                <c:set var="counter" value="${counter + 1}"/>
                                <td>${operation.localDate}</td>
                                <td>${operation.sum}</td>
                                <c:if test="${operation.type == BalanceOperationType.PAYMENT_OF_SUBSCRIPTION}">
                                    <td>${payment_of_subscriptions_operation}</td>
                                </c:if>
                                <c:if test="${operation.type == BalanceOperationType.BALANCE_REPLENISHMENT}">
                                    <td>${balance_replenishment_operation}</td>
                                </c:if>
                                <c:if test="${operation.type == BalanceOperationType.REFUND}">
                                    <td>${refund_operation}</td>
                                </c:if>
                            </tr>
                        </c:forEach>
                    </tbody>
                </table>
            </div>
        </main>
    </div>
</div>
</body>
</html>

src/main/webapp/WEB-INF/jsp/user/profile.jsp
<%--
  Created by IntelliJ IDEA.
  User: lenovo
  Date: 29.07.2022
  Time: 19:32
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<fmt:setLocale value="${sessionScope.locale}"/>
<fmt:bundle basename="localization.local" prefix="balance.">
    <fmt:message key="main_title" var="main_title"/>
    <fmt:message key="sum" var="sum"/>
    <fmt:message key="button" var="button"/>
</fmt:bundle>
<fmt:bundle basename="localization.local" prefix="profile.">
    <fmt:message key="title" var="title"/>
    <fmt:message key="name" var="name"/>
    <fmt:message key="sur_name" var="sur_name"/>
    <fmt:message key="balance" var="balance"/>
    <fmt:message key="email" var="email"/>
    <fmt:message key="money" var="money"/>
</fmt:bundle>

<!DOCTYPE html>
<html>
<head>
    <c:set var="contextPath" value="${pageContext.request.contextPath}"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>${title}</title>
    <link href="<c:url value="/resources/css/bootstrap/bootstrap.min.css" />" rel="stylesheet">
</head>
<body>
<%@include file="/WEB-INF/jsp/nav.jsf" %>
<div class="container-fluid" style="margin-top: 60px">
    <div class="row">

        <%@include file="user-nav.jsf" %>

        <main role="main" class="col-md-9 col-lg-10 px-4">
            <h2>${title}</h2>
            <strong>${name}: </strong> ${user.name}<br/>
            <strong>${sur_name}: </strong> ${user.surName}<br/>
            <strong>${email}: </strong> ${user.email}<br/>
            <br/>
            ${balance}: ${user.balance} ${money}<br/>

            <div class="modal-body">
                <div style="color: red">${error_adding_funds}</div>
                <form action="${pageContext.request.contextPath}/controller/user/replenish-balance" method="post"
                      name="balance" id="balance">
                    <div class="input-group">
                        <span class="input-group-text">${sum}, ${money}:</span>
                        <input class="form-control" type="number" name="sum" pattern="[1-9]{1,3}.?[0-9]{0,2}" step="any"
                               required/>
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <input class="btn btn-primary" id="submit" type="submit" value="${button}"/>
                        </div>
                    </div>
                </form>
            </div>
        </main>
    </div>
</div>
</body>
</html>

src/main/webapp/WEB-INF/jsp/user/subscription_history.jsp
<%--
  Created by IntelliJ IDEA.
  User: lenovo
  Date: 30.07.2022
  Time: 14:33
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java"
         pageEncoding="UTF-8" %>

<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@page import="com.gmail.fursovych20.entity.SubscriptionStatus" %>

<fmt:setLocale value="${sessionScope.locale}"/>
<fmt:bundle basename="localization.local" prefix="subscriptions_page.">
    <fmt:message key="title_subscription_history" var="title"/>
    <fmt:message key="publication_name" var="publication_name"/>
    <fmt:message key="start_date_header" var="start_date_header"/>
    <fmt:message key="end_date_header" var="end_date_header"/>
    <fmt:message key="price_header" var="price_header"/>
    <fmt:message key="status_header" var="status_header"/>
    <fmt:message key="status_terminated" var="status_terminated"/>
    <fmt:message key="status_expired" var="status_expired"/>
    <fmt:message key="show_issues" var="show_issues"/>
    <fmt:message key="no_subscriptions" var="no_subscription"/>
    <fmt:message key="money" var="money"/>
</fmt:bundle>

<c:set var="counter" value="${1}"/>

<!DOCTYPE html>
<html>
<head>
    <c:set var="contextPath" value="${pageContext.request.contextPath}"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>${title}</title>
    <link href="<c:url value="/resources/css/bootstrap/bootstrap.min.css"/>" rel="stylesheet">
</head>
<body>
<%@include file="/WEB-INF/jsp/nav.jsf"%>
<div class="container-fluid" style="margin-top: 60px">
    <div class="row">
        <%@include file="user-nav.jsf"%>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4"><div style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;" class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>

            <h2>${title}</h2>
            <div class="table-responsive">
               <table class="table table-striped table-sm">
                   <thead>
                   <tr>
                       <th>ID</th>
                       <th>${publication_name}</th>
                       <th>${start_date_header}</th>
                       <th>${end_date_header}</th>
                       <th>${price_header}, ${money}</th>
                       <th>${status_header}</th>
                       <th></th>
                   </tr>
                   </thead>
                   <tbody>
                   <c:forEach items="${subscriptions}" var="subscription">
                       <tr>
                           <td>${counter}</td>
                           <c:set var="counter" value="${counter + 1}"/>
                           <td>${publicationNames.get(subscription.publicationId)}</td>
                           <td>${subscription.startLocalDate}</td>
                           <td>${subscription.endLocalDate}</td>
                           <td>${subscription.price}</td>
                           <c:if test="${subscription.status == SubscriptionStatus.EXPIRED}">
                               <td>${status_expired}</td>
                           </c:if>
                           <c:if test="${subscription.status == SubscriptionStatus.TERMINATED}">
                               <td>${status_terminated}</td>
                           </c:if>
                           <td><form method="post" action="${contextPath}/controller/user/show-issues">
                               <input type="hidden" name="subscription_id" value="${subscription.id}"/>
                               <button type="submit" class="btn btn-primary">${show_issues}</button>
                           </form></td>
                       </tr>
                   </c:forEach>
                   </tbody>
               </table>
                <c:if test="${subscription.size() == 0}">
                    <br/>
                    <h3>${no_subscription}</h3>
                </c:if>
            </div>
        </main>
    </div>
</div>

</body>
</html>

src/main/webapp/WEB-INF/jsp/user/subscriptions.jsp
<%--
  Created by IntelliJ IDEA.
  User: lenovo
  Date: 30.07.2022
  Time: 13:05
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java"
         pageEncoding="UTF-8" %>

<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@page import="java.time.LocalDate" %>

<fmt:setLocale value="${sessionScope.locale}"/>
<fmt:bundle basename="localization.local" prefix="subscriptions_page.">
    <fmt:message key="title_active_subscriptions" var="title"/>
    <fmt:message key="publication_name" var="publication_name"/>
    <fmt:message key="start_date_header" var="start_date_header"/>
    <fmt:message key="end_date_header" var="end_date_header"/>
    <fmt:message key="price_header" var="price_header"/>
    <fmt:message key="actions_header" var="actions_header"/>
    <fmt:message key="status_header" var="status_header"/>
    <fmt:message key="action_extend" var="action_extend"/>
    <fmt:message key="action_terminate" var="action_terminate"/>
    <fmt:message key="show_issues" var="show_issues"/>
    <fmt:message key="no_subscriptions" var="no_subscriptions"/>
    <fmt:message key="money" var="money"/>
</fmt:bundle>

<c:set var="counter" value="${1}"/>

<!DOCTYPE html>
<html>
<head>
    <c:set var="contextPath" value="${pageContext.request.contextPath}"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>${title}</title>
    <link href="<c:url value="/resources/css/bootstrap/bootstrap.min.css"/> " rel="stylesheet">
</head>
<body>
<%@include file="/WEB-INF/jsp/nav.jsf" %>

<div class="container-fluid" style="margin-top: 60px">
    <div class="row">
        <%@include file="user-nav.jsf" %>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4"><div style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;" class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>

            <h2>${title}</h2>
            <table class="table table-success table-striped">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">${publication_name}</th>
                <th scope="col">${start_date_header}</th>
                <th scope="col">${end_date_header}</th>
                <th scope="col">${price_header}, ${money}</th>
                <th scope="col" colspan="2">${actions_header}</th>
            </tr>
            </thead>
            <tbody>
            <c:forEach items="${active_subscriptions}" var="subscription">
                <tr>
                    <td scope="row">${counter}</td>
                    <c:set var="counter" value="${counter + 1}"/>
                    <td>${publicationNames.get(subscription.publicationId)}</td>
                    <td>${subscription.startLocalDate}</td>
                    <td>${subscription.endLocalDate}</td>
                    <td>${subscription.price}</td>
                    <c:if test="${subscription.endLocalDate.getMonthValue() - LocalDate.now().getMonthValue() > 0 || subscription.endLocalDate.getYear() > LocalDate.now().getYear()}">
                        <td>
                            <form method="post" action="${contextPath}/controller/user/terminate-subscription">
                                <input type="hidden" name="subscription_id" value="${subscription.id}">
                                <button type="submit" class="btn btn-danger">${action_terminate}</button>
                            </form>
                        </td>
                    </c:if>
                    <c:if test="${subscription.endLocalDate.getMonthValue() - LocalDate.now().getMonthValue() == 0}">
                        <td>
                            <form method="post" action="${contextPath}/controller/publication">
                                <input type="hidden" name="id" value="${subscription.publicationId}"/>
                                <button type="submit" class="btn btn-primary">${action_extend}</button>
                            </form>
                        </td>
                    </c:if>
                    <td>
                        <form method="get" action="${contextPath}/controller/user/show-issues">
                            <input type="hidden" name="subscription_id" value="${subscription.id}">
                            <button type="submit" class="btn btn-primary">${show_issues}</button>
                        </form>
                    </td>
                </tr>
            </c:forEach>
            </tbody>
            <c:if test="${active_subscriptions.size() == 0}">
                <br>
                <h3>${no_subscriptions}</h3>
            </c:if>
        </table>
        </main>
    </div>
</div>
</body>
</html>